### ISSUE TITLE
Get rid of sourceforge download links

### ISSUE THREAD

**Issue by suhr** [winpython/winpython.github.io#26]
Subj.

**Comment by stonebig** [comment]
Github download links are there for people who don't want to use sourceforge.

Sourceforge shows popularity of download links, which github doesn't, and is more practical for me.

I'm open to suggestion for something better, but just geting rid of Sourceforge is not better.

**Comment by suhr** [comment]
Well, at least can GH be presented as the main source?

**Comment by stonebig** [comment]
We have also no true certainty, that Github "likes" to be treated:
- like a Sourceforge download site,
- with such big binaries and quantity of binaries.

Bitbucket; for example, would limit our total downloads to 2Go (or something like that).

The current situation looks to me the most cautious trade-off, until another external event arrives.

**Comment by stonebig** [comment]
Unless Winpython is running downhill quicker, as there are several challenges without answers yet:
- issues to install a node.js package because of node-gyp not compatible with mingwpy,
- issues to provide a portable-usb compiler with an eventual Python 3.5, ...
